# Book settings
title: Level Up Your Python
author: Henry Schreiner

repository:
  url: https://github.com/henryiii/level-up-your-python
  branch: main

execute:
  allow_errors: true

html:
  use_repository_button: true
  
launch_buttons:
  notebook_interface: jupyterlab
