name: level-up-your-python
channels:
  - conda-forge
dependencies:
  - python =3.8
  - pip
  - rich >=9.7
  - pandas >=1.1
  - matplotlib >=3
  - jupyterlab >= 3.0
  - numba >=0.50.0
  - nb_conda_kernels
  - numpy
  - jedi <0.18
  - pip:
    - jupyter-book>=0.9.1
