name: level-up-your-python
channels:
  - conda-forge
dependencies:
  - python ==3.9
  - pip
  - rich >=10.4
  - pandas >=1.3
  - matplotlib >=3
  - jupyterlab >=3
  - numba >=0.54
  - nb_conda_kernels
  - numpy >=1.20
  - ipykernel >=6.0
  - ipywidgets
  - black
  - mypy >=0.930
  - line_profiler
  - jupyter-book
  - filprofiler
  - pybind11>=2.8
  - pytest
  - pytest-mock
