name: level-up-your-python
channels:
  - conda-forge
dependencies:
  - python =3.8
  - pip
  - rich >=9.8
  - pandas >=1.1
  - matplotlib >=3
  - jupyterlab >=3.0
  - numba >=0.50.0
  - nb_conda_kernels
  - numpy >=1.19
  - jedi <0.18
  - xeus-python
  - ipywidgets
  - black
  - mypy >=0.800
  - pip:
    - jupyter-book >=0.9.1
