name: deploy-book

on:
  push:
    branches:
    - main

jobs:
  build-book:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        activate-environment: level-up-your-python

    - name: Install the kernel
      run: |
        python -m ipykernel install --user --name conda-env-level-up-your-python-py

    - name: Build the book
      run: |
        jupyter-book build .

    - uses: actions/upload-artifact@v3
      with:
        name: jupyterbook
        path: _build/html/*


  build-pyodide:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Pyodide output
      run: |
        pipx run nox -s pyodide

    - uses: actions/upload-artifact@v3
      with:
        name: jupyterlite
        path: _output/*


  deploy:
    runs-on: ubuntu-latest
    needs: [build-book, build-pyodide]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: jupyterbook
        path: public

    - uses: actions/download-artifact@v3
      with:
        name: jupyterlite
        path: public/live

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force_orphan: true
